//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::ingredient::Entity as Ingredient;
pub use super::recipe::Entity as Recipe;
pub use super::recipe_ingredient::Entity as RecipeIngredient;
